server:
  port: 8886


# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
spring:
  # 设置为true时，后定义的bean会覆盖之前定义的相同名称的bean
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-demo2?useUnicode=true&characterEncoding=utf8&useSSL=false
    #    driver-class-name: net.sf.log4jdbc.DriverSpy
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:log4jdbc:mysql://localhost:3306/springboot-demo2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 6yhn^YHN
    hikari:
      maximum-pool-size: 30
      minimum-idle: 20
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 900000
  # ===============================
  # = JPA / HIBERNATE
  # ===============================

  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager).

  # Show or not log for each sql query
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL5InnoDBSpatialDialect
#        jdbc:
#          batch_size: 1000
#          batch_versioned_data: true
#        order_inserts: true
#        order_updates: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/springboot-demo

  # email配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 11@qq.com
    password: 11
    from: 11@qq.com
    to: 11@qq.com
    protocol: smtp
    default-encoding: utf-8
    sendPoolSize: 1
    sendTimeout: 30
    open: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5


  redis:
    host: 127.0.0.1
    #默认0的数据库
    database: 1
    port: 6379
    password:

    # 连接超时时间(毫秒)
    timeout: 1000
    pool:
      # 连接池最大连接数(使用负值表示没有限制)
      max-active: 8

      # 连接池中的最大空闲连接
      max-idle: 8

      # 连接池最大阻塞等待时间(使用负值表示没有限制)
      max-wait: -1

      # 连接池中的最小空闲连接
      min-idle: 0

test:
  number: 50
